import React, { useState, useEffect } from 'react';
import { Note, ViewMode } from './types';
import * as noteService from './services/noteService';
import Snow from './components/Snow';
import Tree from './components/Tree';
import WriteModal from './components/WriteModal';
import NoteViewModal from './components/NoteViewModal';
import AdminPanel from './components/AdminPanel';
import NoteList from './components/NoteList';
import { Plus, Eye, Lock, ScrollText } from 'lucide-react';

// Updated tree image URL
const TREE_IMAGE_URL = "https://i.imgur.com/d2eqDEM.png";

const App: React.FC = () => {
  const [notes, setNotes] = useState<Note[]>([]);
  const [viewMode, setViewMode] = useState<ViewMode>(ViewMode.NORMAL);
  const [selectedNote, setSelectedNote] = useState<Note | null>(null);
  const [isWriteModalOpen, setIsWriteModalOpen] = useState(false);
  const [adminPasswordInput, setAdminPasswordInput] = useState('');
  
  // Real-time subscription to notes
  useEffect(() => {
    const unsubscribe = noteService.subscribeToNotes((updatedNotes) => {
      setNotes(updatedNotes);
    });
    return () => unsubscribe();
  }, []);

  const handleAddNote = async (name: string, content: string, ornament: string) => {
    // Generate random position with overlap protection
    
    const minTreeY = 18; 
    const maxTreeY = 88; 
    const MIN_DISTANCE = 6; // Reduced from 10 to allow more ornaments
    const MAX_ATTEMPTS = 100; // Increased attempts to find a spot

    let finalX = 0;
    let finalY = 0;
    let placed = false;

    for (let i = 0; i < MAX_ATTEMPTS; i++) {
      // 1. Pick a random height
      const y = minTreeY + Math.random() * (maxTreeY - minTreeY);
      
      // 2. Calculate the valid width (spread) at this specific height
      const normalizedY = (y - minTreeY) / (maxTreeY - minTreeY);
      
      // Spread factor logic
      const maxSpread = 12 + (normalizedY * 34); 
      
      // 3. Pick a random X within this spread
      const randomOffset = (Math.random() - 0.5) * 2; // -1 to 1
      const x = 50 + (randomOffset * maxSpread);

      // 4. Check collision with existing notes
      const hasCollision = notes.some(note => {
        // Calculate Euclidean distance (approximate since x/y scaling might differ, but good enough)
        const distance = Math.sqrt(
          Math.pow(note.x - x, 2) + 
          Math.pow(note.y - y, 2)
        );
        return distance < MIN_DISTANCE;
      });

      if (!hasCollision) {
        finalX = x;
        finalY = y;
        placed = true;
        break;
      }
    }

    if (!placed) {
      alert("트리가 꽉 차서 더 이상 달 곳이 없어요! 🎄\n다른 오너먼트 사이의 빈 틈을 찾아보세요.");
      return;
    }

    // Create note object without ID (ID is generated by Firebase)
    const newNote = {
      author: name,
      content,
      ornament,
      timestamp: Date.now(),
      x: finalX,
      y: finalY
    };

    try {
      // Save note and get the ID (either from Firebase or LocalStorage fallback)
      const savedId = await noteService.saveNote(newNote);
      
      // Optimistically update the UI immediately
      const noteWithId: Note = { ...newNote, id: savedId };
      setNotes(prev => [...prev, noteWithId]);
      
      setIsWriteModalOpen(false);
    } catch (e) {
      console.error(e);
      // alert handled in service
    }
  };

  const handleDeleteNote = async (id: string) => {
    await noteService.deleteNote(id);
  };

  const handleAdminLogin = (e: React.FormEvent) => {
    e.preventDefault();
    if (adminPasswordInput === 'admin') {
      setViewMode(ViewMode.ADMIN_PANEL);
      setAdminPasswordInput('');
    } else {
      alert('비밀번호가 틀렸습니다.');
    }
  };

  return (
    <div 
      className="min-h-screen font-sans bg-christmas-dark text-white overflow-x-hidden selection:bg-christmas-red selection:text-white bg-cover bg-center bg-fixed relative"
      style={{ backgroundImage: 'url("https://i.imgur.com/n2CqeGJ.png")' }}
    >
      <Snow />

      {/* Main Content */}
      <div className={`transition-all duration-500 ease-in-out ${viewMode === ViewMode.PREVIEW ? 'blur-sm' : ''}`}>
        
        {/* Header - Updated background color */}
        <header className="fixed top-0 w-full z-40 bg-black/40 backdrop-blur-md border-b border-white/10 p-4 flex justify-between items-center">
          <div className="flex items-center gap-2">
            <span className="text-3xl">🎄</span>
            <h1 className="text-2xl font-display font-bold text-christmas-gold tracking-wide hidden sm:block">
              Thanks Tree
            </h1>
          </div>
          
          <div className="flex gap-2">
             {/* List Toggle Button */}
             <button
              onClick={() => setViewMode(viewMode === ViewMode.LIST ? ViewMode.NORMAL : ViewMode.LIST)}
              className={`flex items-center gap-2 px-4 py-2 rounded-full text-sm font-bold transition border ${
                viewMode === ViewMode.LIST 
                  ? 'bg-christmas-gold text-black border-christmas-gold' 
                  : 'bg-white/10 hover:bg-white/20 text-white border-white/20'
              }`}
            >
              <ScrollText size={16} />
              <span className="hidden sm:inline">쪽지 리스트</span>
              <span className="sm:hidden">목록</span>
            </button>

            {/* Preview Button */}
            <button
              onClick={() => setViewMode(ViewMode.PREVIEW)}
              className="flex items-center gap-2 px-4 py-2 bg-white/10 hover:bg-white/20 rounded-full text-sm font-bold transition border border-white/20 text-white"
            >
              <Eye size={16} />
              <span className="hidden sm:inline">전체 보기</span>
              <span className="sm:hidden">보기</span>
            </button>
          </div>
        </header>

        {/* Tree Container 
            Logic: When List mode is active on PC (md+), add padding-right to shift content left
            so the tree is not obscured by the sidebar.
        */}
        <main 
          className={`pt-24 pb-32 px-4 flex flex-col items-center min-h-screen transition-all duration-300 ${
            viewMode === ViewMode.LIST ? 'md:pr-96' : ''
          }`}
        >
          <div className="text-center mb-4 flex flex-col items-center gap-3">
            <img 
              src="https://i.imgur.com/jYKTgK2.png" 
              alt="Thanks Tree Logo"
              className="max-w-[80%] md:max-w-md h-auto drop-shadow-md"
            />
            {/* Secondary Image added below */}
            <img 
              src="https://i.imgur.com/ppF6Zi6.png" 
              alt="Together Logo"
              className="max-w-[60%] md:max-w-xs h-auto drop-shadow-md opacity-90"
            />
          </div>

          <div className="w-full max-w-2xl py-4 flex justify-center">
            <Tree 
              notes={notes} 
              onOrnamentClick={setSelectedNote} 
              isPreview={false}
              imageSrc={TREE_IMAGE_URL}
            />
          </div>

          {/* Description Text - Colors updated to warm amber */}
          <div className="text-center mt-2 mb-8 max-w-md px-4">
            <p className="text-amber-100 whitespace-pre-line leading-relaxed text-lg font-medium bg-black/50 p-4 rounded-xl backdrop-blur-sm border border-white/10 shadow-lg">
              올 한 해, 감사했던 일을 쪽지로 적어 보세요.
              {'\n'}
              우리의 감사한 마음으로 트리를 꾸며보아요!
            </p>
          </div>
        </main>
      </div>

      {/* Floating Action Button - Hide when list is open on mobile to avoid clutter */}
      <div 
        className={`fixed bottom-8 left-1/2 transform -translate-x-1/2 z-30 transition-all duration-300 
        ${viewMode === ViewMode.PREVIEW || (viewMode === ViewMode.LIST && window.innerWidth < 768) ? 'translate-y-40 opacity-0' : 'translate-y-0 opacity-100'}
        ${viewMode === ViewMode.LIST ? 'md:mr-48' : ''} 
        `}
      >
        <button
          onClick={() => setIsWriteModalOpen(true)}
          className="group relative flex items-center gap-3 pl-4 pr-6 py-4 bg-christmas-red hover:bg-red-600 text-white rounded-full shadow-[0_0_20px_rgba(212,36,38,0.6)] hover:shadow-[0_0_30px_rgba(212,36,38,0.8)] transition-all transform hover:scale-105"
        >
          <div className="bg-white/20 p-2 rounded-full">
            <Plus size={24} className="group-hover:rotate-90 transition-transform duration-300" />
          </div>
          <span className="text-lg font-bold">감사 쪽지 작성</span>
        </button>
      </div>

      {/* Note List View (Sidebar/Fullscreen) */}
      {viewMode === ViewMode.LIST && (
        <NoteList 
          notes={notes}
          onClose={() => setViewMode(ViewMode.NORMAL)}
          onNoteClick={(note) => setSelectedNote(note)}
        />
      )}

      {/* Preview Modal */}
      {viewMode === ViewMode.PREVIEW && (
        <div className="fixed inset-0 z-50 bg-black/90 flex flex-col items-center justify-center animate-fade-in">
          <button 
            onClick={() => setViewMode(ViewMode.NORMAL)}
            className="absolute top-6 right-6 text-white/70 hover:text-white p-2"
          >
            <div className="flex flex-col items-center gap-1">
              <span className="text-2xl font-bold">✕</span>
              <span className="text-xs">닫기</span>
            </div>
          </button>
          
          <div className="w-full h-full overflow-hidden flex items-center justify-center">
             <Tree 
              notes={notes} 
              onOrnamentClick={(n) => {
                setSelectedNote(n);
              }} 
              isPreview={true} 
              imageSrc={TREE_IMAGE_URL}
            />
          </div>
          <div className="absolute bottom-10 text-white/50 text-sm">
            전체 트리 미리보기 모드입니다
          </div>
        </div>
      )}

      {/* Note Write Modal */}
      {isWriteModalOpen && (
        <WriteModal 
          onClose={() => setIsWriteModalOpen(false)} 
          onSubmit={handleAddNote}
        />
      )}

      {/* Note View Modal */}
      {selectedNote && (
        <NoteViewModal 
          note={selectedNote} 
          onClose={() => setSelectedNote(null)} 
        />
      )}

      {/* Admin Login Modal */}
      {viewMode === ViewMode.ADMIN_LOGIN && (
        <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/80 backdrop-blur-sm">
          <form onSubmit={handleAdminLogin} className="bg-slate-800 p-8 rounded-xl shadow-2xl w-full max-w-sm border border-slate-700">
            <h3 className="text-xl font-bold mb-4 flex items-center gap-2">
              <Lock size={20} className="text-christmas-gold"/> 관리자 로그인
            </h3>
            <input 
              type="password" 
              value={adminPasswordInput}
              onChange={(e) => setAdminPasswordInput(e.target.value)}
              placeholder="비밀번호를 입력하세요"
              className="w-full bg-slate-900 border border-slate-700 rounded px-4 py-2 mb-4 text-white focus:border-christmas-gold focus:outline-none"
              autoFocus
            />
            <div className="flex justify-end gap-2">
              <button 
                type="button" 
                onClick={() => setViewMode(ViewMode.NORMAL)}
                className="px-4 py-2 text-slate-400 hover:text-white"
              >
                취소
              </button>
              <button 
                type="submit" 
                className="px-4 py-2 bg-christmas-gold text-slate-900 font-bold rounded hover:bg-yellow-400"
              >
                확인
              </button>
            </div>
          </form>
        </div>
      )}

      {/* Admin Panel */}
      {viewMode === ViewMode.ADMIN_PANEL && (
        <AdminPanel 
          notes={notes} 
          onDelete={handleDeleteNote} 
          onClose={() => setViewMode(ViewMode.NORMAL)} 
        />
      )}

      {/* Secret Admin Entry Button (Footer) */}
      <footer className="fixed bottom-0 w-full p-2 flex justify-center opacity-30 hover:opacity-100 transition-opacity z-10 pointer-events-none">
        <button 
          onClick={() => setViewMode(ViewMode.ADMIN_LOGIN)}
          className="pointer-events-auto p-2 text-xs text-slate-500 hover:text-christmas-gold flex items-center gap-1"
        >
          <span>© Thanks Tree Team</span>
          <Lock size={10} className="opacity-50" />
        </button>
      </footer>
    </div>
  );
};

export default App;